name: bar_fit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  googleapis: ^4.0.0
  google_sign_in: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  charts_flutter: ^0.12.0
  flutter_picker_plus: ^1.0.0
  shared_preferences: ^2.0.15
  audioplayers: ^5.2.0
  audioplayers_web: ^4.1.0
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.8
  image_picker: ^1.0.8
  provider: ^6.1.2
  googleapis_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/002.mp3
    - assets/sounds/006.mp3
    - assets/sounds/007.mp3
    - assets/sounds/008.mp3
    - assets/sounds/009.mp3
    - assets/sounds/010.mp3
    - assets/sounds/011.mp3
    - assets/sounds/012.mp3
    - assets/sounds/013.mp3
    - assets/sounds/014.mp3
    - assets/sounds/015.mp3
