name: Flutter CI (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze; exit 0

      - name: Run tests
        run: flutter test

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Create GitHub Release without source code
        run: |
          $tag = "v1.0.${{ github.run_number }}"
          $upload_url = curl -s -X POST https://api.github.com/repos/${{ github.repository }}/releases `
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" `
            -H "Content-Type: application/json" `
            -d "{`"tag_name`":`"$tag`", `"name`":`"Release $tag`", `"body`":`"Automated release`"}" `
            | ConvertFrom-Json | Select-Object -ExpandProperty upload_url
          
          $upload_url = $upload_url -replace '{\?name,label}', ''
          curl -X POST "$upload_url?name=app-release.apk" `
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" `
            -H "Content-Type: application/vnd.android.package-archive" `
            --data-binary "@build/app/outputs/flutter-apk/app-release.apk"
        shell: pwsh
