name: Flutter CI (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze || true

      - name: Run tests
        run: flutter test

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Save local copy of APK
        run: |
          $tag = "v1.0.${{ github.run_number }}"
          $targetDir = "C:\Builds\BarFit\$tag"
          New-Item -ItemType Directory -Force -Path $targetDir
          Copy-Item "build\app\outputs\flutter-apk\app-release.apk" "$targetDir\app-release.apk"
        shell: pwsh

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
